import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'key_01',
    name: '1 Mês',
    description: 'Chave de Acesso • 30 Dias',
    price: 29.90,
    protocol: 'spotify',
  },
  {
    id: 'key_03',
    name: '3 Meses',
    description: 'Chave de Acesso • 90 Dias',
    price: 74.90,
    protocol: 'spotify',
  },
  {
    id: 'key_06',
    name: '6 Meses',
    description: 'Chave de Acesso • 180 Dias',
    price: 139.90,
    protocol: 'spotify',
  },
  /*{
    id: 'tinder_platinum_01',
    name: 'Tinder Platinum 1 Semana',
    description: 'Tinder Platinum • 7 Dias',
    price: 20.00,
    protocol: 'tinder',
  },*/
  {
    id: 'tinder_platinum_02',
    name: 'Tinder Platinum 1 Mês',
    description: 'Tinder Platinum • 30 Dias',
    price: 49.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_platinum_03',
    name: 'Tinder Platinum 6 Meses',
    description: 'Tinder Platinum • 180 Dias',
    price: 189.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_platinum_04',
    name: 'Tinder Platinum 12 Meses',
    description: 'Tinder Platinum • 365 Dias',
    price: 279.90,
    protocol: 'tinder',
  },
  {
    id: 'xbox_gpu_01',
    name: 'Xbox Game Pass Ultimate 1 Mês',
    description: 'Chave de Acesso • 30 Dias',
    price: 63.99,
    protocol: 'xbox',
  },
  {
    id: 'xbox_gpu_account',
    name: 'Conta Xbox Game Pass Ultimate',
    description: 'Conta Compartilhada • Sistema Kami • Distribuição Automatizada • Protocolo Assíncrono • Contas Geradas pelo Sistema • Monitoramento Contínuo • Acesso Pode Ser Perdido Durante Período (7/14/30 dias) • Sem Garantias em Caso de Mau Uso',
    price: 5.00,
    protocol: 'xbox',
  },
  {
    id: 'youtube_premium_family',
    name: 'YouTube Premium Família',
    description: 'Conta Compartilhada • Sistema Kami • Distribuição Automatizada • Protocolo Assíncrono • Contas Geradas pelo Sistema • Monitoramento Contínuo • Acesso Pode Ser Perdido Durante Período (7/14/30 dias) • Sem Garantias em Caso de Mau Uso',
    price: 10.00,
    protocol: 'youtube',
  },
];

export const UI_TEXT = {
  siteTitle: 'Kāmi',
  addToCart: 'Comprar',
  buyNow: 'Executar',
  cart: 'Inventário',
  total: 'Total',
  checkout: 'Processar',
  remove: 'Descartar',
  emptyCart: 'Vazio',
  footer: 'Entrega Criptografada',
  currency: 'R$',
  securePayment: 'Protocolo Seguro',
  spotifyLabel: 'SPOTIFY',
  tinderLabel: 'TINDER',
  xboxLabel: 'XBOX',
  youtubeLabel: 'YOUTUBE',
  digitalAsset: 'ATIVO DIGITAL',
  paymentTitle: 'Terminal de Pagamento',
  confirmPayment: 'Confirmar Transação',
  cancel: 'Cancelar',
  awaiting: 'Verificando...',
  success: 'Sucesso',
  transactionId: 'ID da Transação',
  expiresIn: 'Sessão Expira em',
  status: 'Status',
  statusPending: 'Pagamento Pendente',
  beneficiary: 'Beneficiário',
  bank: 'Instituição',
  reference: 'Referência'
};
