import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'key_01',
    name: 'Spotify Premium 1 Mês',
    description: 'Chave de Acesso • 30 Dias',
    price: 29.90,
    protocol: 'spotify',
  },
  {
    id: 'key_03',
    name: 'Spotify Premium 3 Meses',
    description: 'Chave de Acesso • 90 Dias',
    price: 74.90,
    protocol: 'spotify',
  },
  {
    id: 'key_06',
    name: 'Spotify Premium 6 Meses',
    description: 'Chave de Acesso • 180 Dias',
    price: 139.90,
    protocol: 'spotify',
  },
  /*{
    id: 'tinder_platinum_01',
    name: 'Tinder Platinum 1 Semana',
    description: 'Tinder Platinum • 7 Dias',
    price: 20.00,
    protocol: 'tinder',
  },*/
  {
    id: 'tinder_platinum_01',
    name: 'Tinder Platinum 1 Mês',
    description: 'Tinder Platinum • 30 Dias',
    price: 64.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_platinum_03',
    name: 'Tinder Platinum 3 Meses',
    description: 'Tinder Platinum • 90 Dias',
    price: 169.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_platinum_02',
    name: 'Tinder Platinum 6 Meses',
    description: 'Tinder Platinum • 180 Dias',
    price: 239.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_platinum_03',
    name: 'Tinder Platinum 12 Meses',
    description: 'Tinder Platinum • 365 Dias',
    price: 379.90,
    protocol: 'tinder',
  },    
  {
    id: 'tinder_gold_01',
    name: 'Tinder Gold 1 Semana',
    description: 'Tinder Gold • 7 Dias',
    price: 14.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_gold_02',
    name: 'Tinder Gold 1 Mês',
    description: 'Tinder Gold • 30 Dias',
    price: 26.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_gold_03',
    name: 'Tinder Gold 3 Meses',
    description: 'Tinder Gold • 90 Dias',
    price: 69.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_gold_04',
    name: 'Tinder Gold 6 Meses',
    description: 'Tinder Gold • 180 Dias',
    price: 99.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_gold_05',
    name: 'Tinder Gold 12 Meses',
    description: 'Tinder Gold • 365 Dias',
    price: 149.90,
    protocol: 'tinder',
  },
  //-----------------------------------------
  {
    id: 'tinder_plus_01',
    name: 'Tinder Plus 1 Semana',
    description: 'Tinder Plus • 7 Dias',
    price: 10.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_plus_02',
    name: 'Tinder Plus 1 Mês',
    description: 'Tinder Plus • 30 Dias',
    price: 18.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_plus_03',
    name: 'Tinder Plus 3 Meses',
    description: 'Tinder Plus • 90 Dias',
    price: 49.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_plus_04',
    name: 'Tinder Plus 6 Meses',
    description: 'Tinder Plus • 180 Dias',
    price: 64.90,
    protocol: 'tinder',
  },
  {
    id: 'tinder_plus_05',
    name: 'Tinder Plus 12 Meses',
    description: 'Tinder Plus • 365 Dias',
    price: 99.90,
    protocol: 'tinder',
  },
  {
    id: 'xbox_gpu_01',
    name: 'Xbox Game Pass Ultimate 1 Mês',
    description: 'Chave de Acesso • 30 Dias',
    price: 63.99,
    protocol: 'xbox',
  },
  {
    id: 'xbox_gpu_account',
    name: 'Conta Xbox Game Pass Ultimate',
    description: 'Conta Compartilhada • Sistema Kami • Distribuição Automatizada • Protocolo Assíncrono • Contas Geradas pelo Sistema • Monitoramento Contínuo • Acesso Pode Ser Perdido Durante Período (7/14/30 dias) • Sem Garantias em Caso de Mau Uso',
    price: 10.00,
    protocol: 'xbox',
  },
  {
    id: 'youtube_premium_family',
    name: 'YouTube Premium Família',
    description: 'Conta Compartilhada • Sistema Kami • Distribuição Automatizada • Protocolo Assíncrono • Contas Geradas pelo Sistema • Monitoramento Contínuo • Acesso Pode Ser Perdido Durante Período (7/14/30 dias) • Sem Garantias em Caso de Mau Uso',
    price: 10.00,
    protocol: 'youtube',
  },
];

export const UI_TEXT = {
  siteTitle: 'Kāmi',
  addToCart: 'Comprar',
  buyNow: 'Executar',
  cart: 'Inventário',
  total: 'Total',
  checkout: 'Processar',
  remove: 'Descartar',
  emptyCart: 'Vazio',
  footer: 'Entrega Criptografada',
  currency: 'R$',
  securePayment: 'Protocolo Seguro',
  spotifyLabel: 'SPOTIFY',
  tinderLabel: 'TINDER',
  xboxLabel: 'XBOX',
  youtubeLabel: 'YOUTUBE',
  digitalAsset: 'ATIVO DIGITAL',
  paymentTitle: 'Terminal de Pagamento',
  confirmPayment: 'Confirmar Transação',
  cancel: 'Cancelar',
  awaiting: 'Verificando...',
  success: 'Sucesso',
  transactionId: 'ID da Transação',
  expiresIn: 'Sessão Expira em',
  status: 'Status',
  statusPending: 'Pagamento Pendente',
  beneficiary: 'Beneficiário',
  bank: 'Instituição',
  reference: 'Referência'
};
